### ISSUE TITLE
技術選定について

### ISSUE THREAD

**Issue by kentoiinuma** [kentoiinuma/16type-Favorite-Database#48]
下記のような技術選定で考えているのですが、不適切な点がないか確認していただきたいです。

またReactを使うに当たって、"rails-react"のgemを使って導入するか、RailsのAPIモードを使ってフロントエンドとバックエンドを分けて導入するか、私のPFにはどちらが適切でしょうか？
（またはどちらが就活において評価されるでしょうか？）
アドバイスの方、お願いいたします。

## 機能の実装方針予定  
- フロントエンド
    - React 
    - Tailwind CSS・daisyUI
- バックエンド  
    -  Ruby: 3.0系
	-  Rails: 7.0系
- API 
    - Annict API
    - Spotify API
    - cloudinary
- Gem
	- Googleログイン
		- devise
		- omniauth
	- オートコンプリート
		- stimulus-autocomplete
	- 通知
		- WebSocket通信・ActionCable
    - キューとバックグラウンド処理
	    - ActiveJob
	    - Sidekiq
		- Redis
    - その他
        - Pundit
        - RSpec
        - RuboCop
        - rails-react
- インフラ  
    - Heroku
- データベース
    - PostgreSQL

**Comment by kenchasonakai** [comment]
調べた結果何が違うのか、メリット・デメリットは何があるのか、どちらが良いと思ったのか等を教えていただいて良いでしょうか？

ちなみにGemを使わなくてもyarnなどのパッケージ管理ツールを使ってRailsサーバー上でReactを使えるようにする方法もあります

**Comment by kentoiinuma** [comment]
返信ありがとうございます。

- "rails-react" Gemを使う方法
    - メリット
        - Railsの中で直接Reactを使えるので、設定が少なく始めやすい
    - デメリット
        - ReactがRailsに組み込まれる形で使用されるため、Reactの独立した使用やカスタマイズの柔軟性に制限がある

- RailsのAPIモードでReactを導入する方法
    - メリット
        - Reactの機能を存分に活用でき、フロントエンドとバックエンドが分けられている実務での開発環境に近い形で開発できる
    - デメリット
        - フロントエンドとバックエンドが別れているため、デプロイや環境設定が複雑になる可能性がある
        -  Rails APIモードの習得には追加の学習が必要

- Yarnを使ってRailsサーバー上でReactを使う方法
    - メリット
        - Reactの最新技術を利用可能で、高い柔軟性を持つ
    - デメリット
        - アプリケーションのパフォーマンスが落ちる可能性がある


上記の点を踏まえて、現状、"RailsのAPIモードでReactを導入する方法"で考えています。

**Comment by kenchasonakai** [comment]
デメリットを理解された上での選択だと思うので適切だと思います！

開発頑張ってください👍

**Comment by kentoiinuma** [comment]
ありがとうございます！
